//! Permissive `.feature` file loader for real-world Gherkin exports.
//!
//! [`crate::gherkin::GherkinService::parse`] is strict — it expects
//! one `Feature:` per input and no `# language:` directive that
//! contradicts the keyword set. Real-world Gherkin files in the wild
//! commonly violate both:
//! - codegen tools emit multiple `Feature:` blocks into one file
//! - templates prepend `# language: <code>` directives even when
//!   keywords stay in English
//!
//! This module preprocesses input into chunks the strict parser can
//! swallow, then collects the per-Feature results into a `Vec`.
//!
//! Use [`crate::gherkin::GherkinService::parse`] directly when you
//! need strict mode (a single Feature, no preprocessing) — for
//! example when validating that authors wrote a clean `.feature`
//! file.
//!
//! ## Locale caveat
//!
//! [`parse_relaxed`] assumes English-keyword Gherkin. The
//! `# language:` strip means that a file written with non-English
//! keywords (e.g. real `功能:` / `情境:` zh-TW Gherkin) will fail to
//! parse after preprocessing. For that case, call
//! [`crate::gherkin::GherkinService::parse`] directly.

use std::path::Path;

use crate::error::Result;
use crate::gherkin::{GherkinService, ParsedFeature};

/// Load a `.feature` file from disk and parse it permissively.
/// Returns one [`ParsedFeature`] per top-level `Feature:` block found
/// in the file. See [`parse_relaxed`] for the preprocessing rules.
pub fn load_file(path: &Path) -> Result<Vec<ParsedFeature>> {
    let content = std::fs::read_to_string(path)?;
    parse_relaxed(&content)
}

/// Parse a `.feature`-shaped string into one or more
/// [`ParsedFeature`]s.
///
/// Preprocessing applied before reaching `GherkinService::parse`:
/// - any `# language:` directive line is stripped
/// - the input is split on each line beginning with `Feature:`, so
///   files carrying multiple Features parse into multiple results
///
/// Chunks that contain no `Feature:` line (e.g. a leading comment
/// block before the first Feature) are skipped.
pub fn parse_relaxed(content: &str) -> Result<Vec<ParsedFeature>> {
    let preprocessed = strip_language_directives(content);
    split_features(&preprocessed)
        .into_iter()
        .filter(|c| c.contains("Feature:"))
        .map(|c| GherkinService::parse(&c))
        .collect()
}

fn strip_language_directives(s: &str) -> String {
    s.lines()
        .filter(|line| !line.trim_start().starts_with("# language:"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn split_features(s: &str) -> Vec<String> {
    let mut chunks: Vec<String> = Vec::new();
    let mut current = String::new();
    for line in s.lines() {
        if line.starts_with("Feature:") && !current.trim().is_empty() {
            chunks.push(std::mem::take(&mut current));
        }
        current.push_str(line);
        current.push('\n');
    }
    if !current.trim().is_empty() {
        chunks.push(current);
    }
    chunks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_language_directive_before_parsing() {
        let input = "\
# language: zh-TW
Feature: hello
  Scenario: ok
    Given x
";
        let result = parse_relaxed(input).expect("must parse");
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].name, "hello");
    }

    #[test]
    fn splits_multi_feature_input_into_separate_results() {
        let input = "\
Feature: A
  Scenario: a1
    Given x

Feature: B
  Scenario: b1
    Given y
";
        let result = parse_relaxed(input).expect("must parse");
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].name, "A");
        assert_eq!(result[1].name, "B");
    }

    #[test]
    fn skips_leading_comment_chunk_before_first_feature() {
        let input = "\
# auto-generated by codegen — do not edit
# another comment line

Feature: X
  Scenario: x1
    Given x
";
        let result = parse_relaxed(input).expect("must parse");
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].name, "X");
    }
}
